import { readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { pathToFileURL } from "node:url";

type Paths = Record<string, string[]>;
interface Profile {
  file: string;
  extends: string[];
  aliases: Paths;
}

/** TS replaces paths maps wholesale. Materialize sparse runtime overrides from one shared map. */
export function sourceCheckProfile(paths: Paths, profile: Profile): string {
  return (
    JSON.stringify(
      {
        $comment:
          "Generated by scripts/source-check-config.ts; edit tsconfig.source.json or source-check-profiles.json, then run pnpm quality:configs:write.",
        extends: profile.extends,
        compilerOptions: { paths: { ...paths, ...profile.aliases } },
      },
      null,
      2,
    ) + "\n"
  );
}
export function checkSourceProfiles(root: string, write = false): string[] {
  const base = JSON.parse(
    readFileSync(resolve(root, "tsconfig.source.json"), "utf8"),
  ) as { compilerOptions: { paths: Paths } };
  const profiles = JSON.parse(
    readFileSync(resolve(root, "source-check-profiles.json"), "utf8"),
  ) as Profile[];
  const stale: string[] = [];
  for (const profile of profiles) {
    const output = sourceCheckProfile(base.compilerOptions.paths, profile);
    const file = resolve(root, profile.file);
    if (write) writeFileSync(file, output);
    else {
      let existing: string | undefined;
      try {
        existing = readFileSync(file, "utf8");
      } catch {
        /* Missing generated config is stale too. */
      }
      if (existing !== output) stale.push(profile.file);
    }
  }
  return stale;
}
if (
  process.argv[1] &&
  import.meta.url === pathToFileURL(resolve(process.argv[1])).href
) {
  const stale = checkSourceProfiles(
    process.cwd(),
    process.argv.includes("--write"),
  );
  if (stale.length) {
    console.error(
      `Source-check profiles are stale: ${stale.join(", ")}. Run pnpm quality:configs:write.`,
    );
    process.exitCode = 1;
  }
}
